[package]
name = "rustup-toolchain-manifest"
authors = ["Francis Russell <francis@unchartedbackwaters.co.uk>"]
version = "0.2.2"
edition = "2021"
license = "BSD-3-Clause"
description = "Parses the Rust toolchain manifest"
keywords = ["toolchain", "manifest"]
repository = "https://github.com/FrancisRussell/rustup-toolchain-manifest.git"

[dependencies]
basic-toml = "0.1.0"
chrono = { version = "0.4.23", default-features = false, features = [ "serde" ] }
platforms = { default-features = false, version = "3.7.0" }
serde = { version = "1.0.147", features = ["derive"] }
thiserror = "2.0.0"

[dev-dependencies]
clap = { version = "4.0.26", features = [ "derive" ] }
reqwest = { version = "0.13.0", features = ["blocking"] }
